name: Dependency-Check

on:
  push:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: macos-latest

    steps:
    - name: Check workflow initialization source
      if: ${{ github.actor != 'github-actions' }}
      run: exit 0
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install Dependencies
      run: pod install

    - name: Install OWASP Dependency-Check
      run: brew install dependency-check

    - name: Run Dependency-Check
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: |
        ./dependency-check.sh

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ./dependency-check-report

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Add Dependency-Check report"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
